"""add_pa_and_referral_models

Revision ID: 524c8b2a7cd4
Revises: 0002_cases_intake
Create Date: 2025-12-24 12:54:40.319904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '524c8b2a7cd4'
down_revision = '0002_cases_intake'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('referring_provider', sa.String(length=255), nullable=True),
    sa.Column('target_specialty', sa.String(length=255), nullable=True),
    sa.Column('clinical_urgency', sa.String(length=32), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_referrals_tenant', 'referrals', ['tenant_id'], unique=False)
    op.create_table('prior_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=True),
    sa.Column('procedure_code', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prior_auth_tenant', 'prior_authorizations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prior_auth_tenant', table_name='prior_authorizations')
    op.drop_table('prior_authorizations')
    op.drop_index('ix_referrals_tenant', table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('integration_credentials')
    # ### end Alembic commands ###
